version: 2
updates:
  - package-ecosystem: cargo
    directory: "/rearch"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/rearch-macros"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/rearch-tokio"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/examples/axum"
    schedule:
      interval: weekly
