version: 2
updates:
  - package-ecosystem: cargo
    directory: "/rearch"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/rearch-capsule-macro"
    schedule:
      interval: weekly
