[package]
name = "example-axum"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
rearch = { workspace = true }
axum = "0.7.*"
redb = "1.*"
serde = { version = "1.*", features = ["derive"] }
tokio = { version = "1.*", features = ["full"] }
uuid = { version = "1.*", features = ["v4", "serde"] }
