[package]
name = "rearch"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true
readme.workspace = true

[dependencies]
rearch-macros = { workspace = true }
concread = { version = "0.4.*", default-features = false, features = ["maps"] }
dyn-clone = "1.*"
paste = "1.*"
log = { version = "0.4.*", optional = true }
tokio = { version = "1.*", default-features = false, features = ["rt"], optional = true }

[features]
default = []
logging = ["dep:log"]
tokio-side-effects = ["dep:tokio"]
