[package]
name = "rearch"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
concread = { version = "0.4.*", default-features = false, features = ["maps"] }
dyn-clone = "1.*"
paste = "1.*"
rearch-capsule-macro = { workspace = true, optional = true }
tokio = { version = "1.*", default-features = false, features = ["rt"], optional = true }

[features]
default = ["capsule-macro"]
capsule-macro = ["dep:rearch-capsule-macro"]
tokio-side-effects = ["dep:tokio"]
